### ISSUE TITLE
incompatible with DoH on windows

### ISSUE THREAD

**Issue by LZY2006** [macronut/ghostcp#31]
![image](https://user-images.githubusercontent.com/58110034/165898719-86a7417c-0cb8-43a6-a0af-dfab05ba803e.png)
设置完之后无法访问Google这种被SNI阻断的网站，被DNS污染和中国国内的网站正常。

**Comment by macronut** [comment]
If you use DoH on your system or browser, then ghostcp can no longer get or modify DNS records, you need to set the IP of the domain you want to visit with hosts.
