### ISSUE TITLE
连接 mega时出现 SSL_ERROR_BAD_MAC_READ

### ISSUE THREAD

**Issue by sqsa1** [macronut/ghostcp#32]
连接 mega时出现 SSL_ERROR_BAD_MAC_READ

**Comment by Longway22** [comment]
试试 method 里加上 df 。

**Comment by macronut** [comment]
Mega's servers are so badly configured that not only can they not be sliced and some browsers will re-handshake, so ”Don't Fragment“ and handling subsequent communications (sat) is necessary.
