### ISSUE TITLE
ghostcp会与一些本地反代方案产生错误

### ISSUE THREAD

**Issue by yuijker** [macronut/ghostcp#37]
在使用一些本地反代方案访问时，我发现ghostcp会直接抢走进入反代的流量，出现大量的错误
Error code: tcp.go:545: The parameter is incorrect.
这是一个反代方案：https://github.com/mashirozx/Pixiv-Nginx
以上面的反代去访问pixiv.net为例
安装好反代方案后尝试打开网站：

![屏幕截图 2022-10-26 160547](https://user-images.githubusercontent.com/72558803/197970245-4355cd48-2eca-436e-ad01-874ce0459108.png)

没有问题
然后加入ghostcp

![image](https://user-images.githubusercontent.com/72558803/197970578-adcc2605-ebe5-4ba8-8f82-720f6aacc091.png)

ghostcp：
![image](https://user-images.githubusercontent.com/72558803/197970636-2806a736-fb41-4701-b097-24bd3232c555.png)

信息补充：
系统：windows10 20H2
浏览器：edge 106.0.1370.52

**Comment by Longway22** [comment]
建议不用反代了，让ghostcp接管这些域名。
Pixiv 是吧，下面这段加到配置里。
```
.pixiv.net
.pximg.net
```

**Comment by macronut** [comment]
If you want to use your reverse proxy don't configure it in ghostcp, and there is no need for a reverse proxy when using ghostcp.
