### ISSUE TITLE
chrome浏览器没有使用ghostcp

### ISSUE THREAD

**Issue by yuijker** [macronut/ghostcp#38]
基本信息：
系统：windows 10 20H2
浏览器：chrome 107.0.5304.88
问题：
当我在启动ghostcp后使用chrome浏览器访问已设定的网站时，chrome没有将网站流量导向ghostcp，导致超时。我这里以维基百科为例：

![image](https://user-images.githubusercontent.com/72558803/198512684-d37019a7-fe77-4879-a8ad-b5b880944683.png)

![image](https://user-images.githubusercontent.com/72558803/198512908-76a8e621-939f-479f-baab-dcbc3f2337fc.png)

conf文件：
![image](https://user-images.githubusercontent.com/72558803/198513003-d2fc07cd-4396-4e97-b521-40c44acd4655.png)

作为对比的edge 107.0.1418.24 

![image](https://user-images.githubusercontent.com/72558803/198513185-4ed1c8cd-85cd-49cf-a795-04169a26d63d.png)

![image](https://user-images.githubusercontent.com/72558803/198513236-f196e8d7-2a35-4d52-9882-d6337972a668.png)

**Comment by macronut** [comment]
Disable DoH on Chrome
