### ISSUE TITLE
Where is tcpioneer.exe ??

### ISSUE THREAD

**Issue by lulMeow** [macronut/ghostcp#43]
Hi,
you said "run tcpioneer.exe to start the program" but there is no `tcpioneer.exe` in the Source code(zip) file or anywhere in the repository.

**Comment by UnCLAS-Prommer** [comment]
You can download the source code and compile by yourself.
Then put the .exe file in the release folder.

**Comment by macronut** [comment]
https://github.com/macronut/ghostcp/issues/42
