### ISSUE TITLE
如何在配置文件中导入ipv6地址

### ISSUE THREAD

**Issue by QvPing** [macronut/ghostcp#46]
如何在配置文件中导入ipv6地址？直接把ipv4地址改成ipv6地址并用“，”分割会提示bad domin. 怎样才能正确导入ipv6地址呢？

**Comment by macronut** [comment]
The IP address is not a URL, [] is not required, this symbol indicates in the configuration that the domain uses the addresses of another domain.

https://en.wikipedia.org/wiki/IPv6_address
