### ISSUE TITLE
对有些http链接无效

### ISSUE THREAD

**Issue by zhengqwe** [macronut/ghostcp#49]
无论用什么方法都会rst

**Comment by zhengqwe** [comment]
> 这种情况确实是存在的。但是鉴于现在纯HTTP而且也被封锁的网站太少，我就举几个例子好了。
> 
> ```
> feng.jp
> www.ehviewer.com
> www.dalailamaworld.com
> rmjdw.com
> redchinacn.org
> ```
> 
> 如同在维基百科Telegram群描述的那样，对于纯HTTP网站的TCB desync尝试一般会成功一次，但之后就会不断被重置。我是通过phantomsocks测试的，ghostcp应该也差不多。

要是能把rst强行丢掉就好了

**Comment by UjuiUjuMandan** [comment]
@zhengqwe 奇怪的是，咱这边用 phantomsocks 测试上述域名没有发现访问问题。请问您是什么域名无法访问？

**Comment by UjuiUjuMandan** [comment]
> 要是能把rst强行丢掉就好了

不行的哦，rst 是双向发送。

**Comment by zhengqwe** [comment]
> @zhengqwe 奇怪的是，咱这边用 phantomsocks 测试上述域名没有发现访问问题。请问您是什么域名无法访问？

`bugs.qbittorrent.org`

**Comment by UjuiUjuMandan** [comment]
> `bugs.qbittorrent.org`

我猜测您可能使用了中国移动的网络，他们会时不时随机屏蔽一些国外域名。
这个域名我这里测试并没有被封锁，因此无法帮到您，抱歉啦。

**Comment by zhengqwe** [comment]
> > 要是能把rst强行丢掉就好了
> 
> 不行的哦，rst 是双向发送。

我刚才举的那个例子就是单向的，有时抓包能抓到正常响应

**Comment by zhengqwe** [comment]
> > > 要是能把rst强行丢掉就好了
> > 
> > 
> > 不行的哦，rst 是双向发送。
> 
> 我刚才举的那个例子就是单向的，有时抓包能抓到正常响应，就是有时`no-rst`有漏网之鱼
